// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lockups/Layer.tsx": () => import("../components/mockups/lockups/Layer.tsx"),
  "./components/mockups/lockups/Network.tsx": () => import("../components/mockups/lockups/Network.tsx"),
  "./components/mockups/lockups/Signet.tsx": () => import("../components/mockups/lockups/Signet.tsx"),
  "./components/mockups/lockups/Wordmark.tsx": () => import("../components/mockups/lockups/Wordmark.tsx")
};
